from enum import Enum


class ExerciseName(str, Enum):
    '''Enum for ExerciseName values.'''

    HIP_ABDUCTION_MACHINE = "Hip Abduction Machine"
    CABLE_HIP_ABDUCTION = "Cable Hip Abduction"
    LYING_FLOOR_LEG_RAISE = "Lying Floor Leg Raise"
    CABLE_CRUNCH = "Cable Crunch"
    WEIGHTED_CRUNCH = "Weighted Crunch"
    DUMBBELL_SIDE_BENDS = "Dumbbell Side Bends"
    PLANK = "Plank"
    HANGING_LEG_RAISE = "Hanging Leg Raise"
    SIT_UP = "Sit Up"
    BARBELL_ABDOMINAL_ROLLOUTS = "Barbell Abdominal Rollouts"
    AB_CRUNCH = "Ab Crunch"
    DECLINE_BENCH_SIT_UP = "Decline Bench Sit Up"
    ABDOMINAL_AIR_BIKE_AKA_BICYCLE = "Abdominal Air Bike AKA Bicycle"
    SIDE_PLANK = "Side Plank"
    EXERCISE_BALL_CRUNCH = "Exercise Ball Crunch"
    RUSSIAN_TWIST = "Russian Twist"
    FLOOR_CRUNCH_LEGS_ON_BENCH = "Floor Crunch legs on bench"
    ROTATING_MOUNTAIN_CLIMBER = "Rotating Mountain Climber"
    HANGING_KNEE_RAISE_WITH_TWIST = "Hanging Knee Raise With Twist"
    HANGING_KNEE_RAISE = "Hanging Knee Raise"
    PLANK_TO_HIP_RAISE = "Plank to Hip Raise"
    SEATED_BARBELL_TWIST = "Seated Barbell Twist"
    PALLOF_PRESS = "Pallof Press"
    STANDING_STOMACH_VACUUM = "Standing Stomach Vacuum"
    LYING_FLOOR_KNEE_TUCK = "Lying Floor Knee Tuck"
    ALTERNATE_STRAIGHT_LEG_LOWER = "Alternate Straight Leg Lower"
    DEAD_BUG = "Dead Bug"
    ABOMINAL_HIP_THRUST = "Abominal Hip Thrust"
    ROMAN_CHAIR_LEG_RAISE = "Roman Chair Leg Raise"
    LYING_LEG_RAISE_WITH_HIP_THRUST = "Lying Leg Raise With Hip Thrust"
    HOLLOW_BODY_HOLD = "Hollow Body Hold"
    DECLINE_BENCH_ABDOMINAL_REACH = "Decline Bench Abdominal Reach"
    HIP_ADDUCTION_MACHINE = "Hip Adduction Machine"
    DEEP_SQUAT_PRYING = "Deep Squat Prying"
    CABLE_HIP_ADDUCTION = "Cable Hip Adduction"
    ROCKING_FROG_STRETCH = "Rocking Frog Stretch"
    ALTERNATING_LATERAL_LUNGE_WITH_OVERHEAD_REACH = "Alternating Lateral Lunge with Overhead Reach"
    LATERAL_KNEELING_ADDUCTOR_MOBILIZATION = "Lateral Kneeling Adductor Mobilization"
    ADDUCTOR_FOAM_ROLLING = "Adductor Foam Rolling"
    STANDING_HAMMER_CURL = "Standing Hammer Curl"
    STANDING_DUMBBELL_CURL = "Standing Dumbbell Curl"
    INCLINE_DUMBBELL_CURL = "Incline Dumbbell Curl"
    STANDING_BARBELL_CURL = "Standing Barbell Curl"
    ZOTTMAN_CURL = "Zottman Curl"
    CABLE_CURL = "Cable Curl"
    CROSS_BODY_HAMMER_CURL_PINWHEEL_CURLS = "Cross Body Hammer Curl Pinwheel Curls"
    EZ_BAR_PREACHER_CURL = "EZ Bar Preacher Curl"
    CONCENTRATION_CURL = "Concentration Curl"
    BARBELL_PREACHER_CURL = "Barbell Preacher Curl"
    CABLE_CURL_ROPE_EXTENSION = "Cable Curl Rope Extension"
    EZ_BAR_CURL = "EZ Bar Curl"
    SPIDER_CURL = "Spider Curl"
    ALTERNATING_STANDING_DUMBBELL_CURL = "Alternating Standing Dumbbell Curl"
    ALTERNATING_SEATED_DUMBBELL_CURL = "Alternating Seated Dumbbell Curl"
    MACHINE_BICEP_CURL = "Machine Bicep Curl"
    STANDING_DUMBBELL_REVERSE_CURL = "Standing Dumbbell Reverse Curl"
    SEATED_DUMBBELL_CURL = "Seated Dumbbell Curl"
    STANDING_HIGH_PULLEY_CABLE_CURL = "Standing High Pulley Cable Curl"
    DUMBBELL_HAMMER_PREACHER_CURL = "Dumbbell Hammer Preacher Curl"
    ALTERNATING_STANDING_HAMMER_CURL = "Alternating Standing Hammer Curl"
    SEATED_HAMMER_CURL = "Seated Hammer Curl"
    ONEARM_SEATED_DUMBBELL_CURL = "OneArm Seated Dumbbell Curl"
    DUMBBELL_PREACHER_CURL = "Dumbbell Preacher Curl"
    SMITH_MACHINE_BICEP_CURL = "Smith Machine Bicep Curl"
    CABLE_PREACHER_CURL = "Cable Preacher Curl"
    ONEARM_STANDING_HAMMER_CURL = "OneArm Standing Hammer Curl"
    WIDE_GRIP_STANDING_BARBELL_CURL = "Wide Grip Standing Barbell Curl"
    BARBELL_DRAG_CURL = "Barbell Drag Curl"
    ONEARM_CABLE_CURL = "OneArm Cable Curl"
    SEATED_CALF_RAISE = "Seated Calf Raise"
    SEATED_DUMBBELL_CALF_RAISE = "Seated Dumbbell Calf Raise"
    _45_DEGREE_LEG_PRESS_CALF_RAISE = "45 Degree Leg Press Calf Raise"
    STANDING_BARBELL_CALF_RAISE = "Standing Barbell Calf Raise"
    BODYWEIGHT_STANDING_CALF_RAISE = "Bodyweight Standing Calf Raise"
    STANDING_MACHINE_CALF_RAISE = "Standing Machine Calf Raise"
    STANDING_ONELEG_CALF_RAISE_WITH_DUMBBELL = "Standing OneLeg Calf Raise With Dumbbell"
    ONELEG_SEATED_DUMBBELL_CALF_RAISE = "OneLeg Seated Dumbbell Calf Raise"
    SMITH_MACHINE_CALF_RAISE = "Smith Machine Calf Raise"
    DONKEY_CALF_RAISE = "Donkey Calf Raise"
    ONELEG_STANDING_BODYWEIGHT_CALF_RAISE = "OneLeg Standing Bodyweight Calf Raise"
    BANDED_TIBIALIS_RAISE = "Banded Tibialis Raise"
    JUMP_ROPE = "Jump Rope"
    SMITH_MACHINE_SEATED_CALF_RAISE = "Smith Machine Seated Calf Raise"
    CABLE_CALF_RAISE = "Cable Calf Raise"
    HACK_SQUAT_CALF_RAISE = "Hack Squat Calf Raise"
    ROCKING_STANDING_CALF_RAISE = "Rocking Standing Calf Raise"
    BODYWEIGHT_FLOOR_CALF_RAISE = "Bodyweight Floor Calf Raise"
    PERONEAL_FOAM_ROLLING = "Peroneal Foam Rolling"
    STANDING_BARBELL_CALF_RAISE_ON_FLOOR = "Standing Barbell Calf Raise On Floor"
    SIDE_TO_SIDE_JUMP_ROPE = "Side to Side Jump Rope"
    INCLINE_DUMBBELL_BENCH_PRESS = "Incline Dumbbell Bench Press"
    DUMBBELL_BENCH_PRESS = "Dumbbell Bench Press"
    DUMBBELL_PULLOVER = "Dumbbell Pullover"
    DUMBBELL_FLYS = "Dumbbell Flys"
    BARBELL_BENCH_PRESS = "Barbell Bench Press"
    PEC_DECK = "Pec Deck"
    INCLINE_BENCH_PRESS = "Incline Bench Press"
    CLOSE_GRIP_DUMBBELL_PRESS_AKA_CRUSH_PRESS = "Close Grip Dumbbell Press AKA Crush Press"
    STANDING_CABLE_FLY = "Standing Cable Fly"
    REVERSE_GRIP_DUMBBELL_BENCH_PRESS = "Reverse Grip Dumbbell Bench Press"
    HAMMER_STRENGTH_BENCH_PRESS = "Hammer Strength Bench Press"
    INCLINE_DUMBBELL_FLYS = "Incline Dumbbell Flys"
    CHEST_DIP = "Chest Dip"
    CABLE_CROSSOVERS_UPPER_CHEST = "Cable Crossovers Upper Chest"
    CABLE_IRON_CROSS = "Cable Iron Cross"
    PUSH_UP = "Push Up"
    STANDING_LOW_TO_HIGH_CABLE_FLY = "Standing Low to High Cable Fly"
    HAMMER_STRENGTH_MACHINE_INCLINE_BENCH_PRESS = "Hammer Strength Machine Incline Bench Press"
    DECLINE_BENCH_PRESS = "Decline Bench Press"
    DECLINE_DUMBBELL_BENCH_PRESS = "Decline Dumbbell Bench Press"
    SMITH_MACHINE_INCLINE_BENCH_PRESS = "Smith Machine Incline Bench Press"
    STANDING_HIGH_TO_LOW_CABLE_FLY = "Standing High to Low Cable Fly"
    CABLE_CHEST_PRESS = "Cable Chest Press"
    ONE_ARM_DUMBBELL_FLY = "One Arm Dumbbell Fly"
    PLYOMETRIC_PUSH_UP = "Plyometric Push Up"
    SMITH_MACHINE_BENCH_PRESS = "Smith Machine Bench Press"
    DECLINE_PUSH_UP_FEET_ON_BENCH = "Decline Push Up Feet on Bench"
    WEIGHTED_CHEST_DIP = "Weighted Chest Dip"
    NEUTRAL_GRIP_DUMBBELL_BENCH_PRESS = "Neutral Grip Dumbbell Bench Press"
    BARBELL_PULLOVER = "Barbell Pullover"
    LAT_PULL_DOWN = "Lat Pull Down"
    CLOSE_GRIP_LAT_PULL_DOWN = "Close Grip Lat Pull Down"
    WIDE_GRIP_PULL_UP = "Wide Grip Pull Up"
    STRAIGHT_ARM_LAT_PULL_DOWN = "Straight Arm Lat Pull Down"
    CHIN_UP = "Chin Up"
    WIDE_GRIP_LAT_PULL_DOWN = "Wide Grip Lat Pull Down"
    PULL_UP = "Pull Up"
    REVERSE_GRIP_LAT_PULL_DOWN_UNDERHAND = "Reverse Grip Lat Pull Down Underhand"
    ROPE_STRAIGHT_ARM_PULL_DOWN = "Rope Straight Arm Pull Down"
    VBAR_PULL_DOWN = "VBar Pull Down"
    SHOTGUN_ROW = "Shotgun Row"
    ECCENTRIC_ONLY_PULL_UP = "Eccentric Only Pull Up"
    VBAR_PULL_UP = "VBar Pull Up"
    WEIGHTED_PULL_UP = "Weighted Pull Up"
    RACK_LAT_STRETCH = "Rack Lat Stretch"
    BAND_ASSISTED_CHIN_UP_FROM_FOOT = "Band Assisted Chin Up From Foot"
    RESISTANCE_BAND_ASSISTED_PULL_UP_FROM_FOOT = "Resistance Band Assisted Pull Up From Foot"
    UNDERHAND_CLOSE_GRIP_LATERAL_PULLDOWN = "Underhand Close Grip Lateral Pulldown"
    CLOSE_GRIP_PULL_UP = "Close Grip Pull Up"
    RESISTANCE_BAND_ASSISTED_PULL_UP_FROM_KNEE = "Resistance Band Assisted Pull Up From Knee"
    WEIGHTED_CHIN_UP = "Weighted Chin Up"
    BEHIND_NECK_LAT_PULL_DOWN = "Behind Neck Lat Pull Down"
    STANDING_OVERHEAD_MEDICINE_BALL_SLAM = "Standing Overhead Medicine Ball Slam"
    PULL_UP_WITH_LEG_RAISE = "Pull Up with Leg Raise"
    THIBAUDEAU_KAYAK_ROW = "Thibaudeau Kayak Row"
    LATERAL_PULLDOWN_ROPE_EXTENSION = "Lateral Pulldown Rope Extension"
    ARCHER_PULL_UP = "Archer Pull Up"
    OVERHAND_CLOSE_GRIP_LATERAL_PULLDOWN = "Overhand Close Grip Lateral Pulldown"
    ARMS_ONLY_ROPE_CLIMB = "Arms Only Rope Climb"
    SKIN_THE_CAT = "Skin the Cat"
    NECK_TIGER_TAIL = "Neck Tiger Tail"
    DUMBBELL_LATERAL_RAISE = "Dumbbell Lateral Raise"
    MILITARY_PRESS_AKA_OVERHEAD_PRESS = "Military Press AKA Overhead Press"
    BENT_OVER_DUMBBELL_REVERSE_FLY = "Bent Over Dumbbell Reverse Fly"
    SEATED_ARNOLD_PRESS = "Seated Arnold Press"
    STANDING_DUMBBELL_SHOULDER_PRESS = "Standing Dumbbell Shoulder Press"
    SEATED_DUMBBELL_PRESS = "Seated Dumbbell Press"
    SMITH_MACHINE_SHOULDER_PRESS = "Smith Machine Shoulder Press"
    SEATED_BENT_OVER_DUMBBELL_REVERSE_FLY = "Seated Bent Over Dumbbell Reverse Fly"
    SEATED_BARBELL_SHOULDER_PRESS = "Seated Barbell Shoulder Press"
    CABLE_FACE_PULL = "Cable Face Pull"
    SEATED_DUMBBELL_LATERAL_RAISE = "Seated Dumbbell Lateral Raise"
    STANDING_CABLE_REVERSE_FLY = "Standing Cable Reverse Fly"
    MACHINE_REVERSE_FLY = "Machine Reverse Fly"
    STANDING_DUMBBELL_FRONT_RAISE = "Standing Dumbbell Front Raise"
    MACHINE_SHOULDER_PRESS = "Machine Shoulder Press"
    CABLE_LATERAL_RAISE = "Cable Lateral Raise"
    SEATED_BEHIND_THE_NECK_SHOULDER_PRESS = "Seated Behind the Neck Shoulder Press"
    SINGLE_ARM_CABLE_LATERAL_RAISE_CROSSBODY = "Single Arm Cable Lateral Raise Crossbody"
    MACHINE_LATERAL_RAISE = "Machine Lateral Raise"
    BARBELL_FRONT_RAISE = "Barbell Front Raise"
    ONEARM_DUMBBELL_LATERAL_RAISE = "OneArm Dumbbell Lateral Raise"
    CABLE_UPRIGHT_ROW = "Cable Upright Row"
    SMITH_MACHINE_UPRIGHT_ROW = "Smith Machine Upright Row"
    STANDING_ARNOLD_PRESS = "Standing Arnold Press"
    BENT_OVER_LOW_PULLEY_REAR_DELT_FLY = "Bent Over Low Pulley Rear Delt Fly"
    BAND_PULL_APART = "Band Pull Apart"
    WEIGHT_PLATE_FRONT_RAISE = "Weight Plate Front Raise"
    DUMBBELL_UPRIGHT_ROW = "Dumbbell Upright Row"
    SEATED_NEUTRAL_GRIP_DUMBBELL_SHOULDER_PRESS = "Seated Neutral Grip Dumbbell Shoulder Press"
    STRAIGHT_BAR_TRICEP_EXTENSION = "Straight Bar Tricep Extension"
    LYING_DUMBBELL_EXTENSION = "Lying Dumbbell Extension"
    SEATED_DUMBBELL_TRICEP_EXTENSION = "Seated Dumbbell Tricep Extension"
    ROPE_TRICEP_EXTENSION = "Rope Tricep Extension"
    DUMBBELL_FLOOR_PRESS = "Dumbbell Floor Press"
    EZ_BAR_SKULLCRUSHER = "EZ Bar Skullcrusher"
    TRICEP_DIP = "Tricep Dip"
    TWO_ARM_STANDING_DUMBBELL_EXTENSION = "Two Arm Standing Dumbbell Extension"
    CLOSE_GRIP_BENCH_PRESS = "Close Grip Bench Press"
    LYING_BARBELL_TRICEP_EXTENSION_SKULL_CRUSHER = "Lying Barbell Tricep Extension Skull Crusher"
    BENT_OVER_DUMBBELL_TRICEP_KICKBACK = "Bent Over Dumbbell Tricep Kickback"
    FRENCH_PRESS = "French Press"
    ONEARM_STANDING_DUMBBELL_EXTENSION = "OneArm Standing Dumbbell Extension"
    DUMBBELL_TRICEP_KICKBACK = "Dumbbell Tricep Kickback"
    STANDING_LOW_PULLEY_OVERHEAD_TRICEP_EXTENSION_ROPE_EXTENSION = "Standing Low Pulley Overhead Tricep Extension Rope Extension"
    INCLINE_SKULL_CRUSHER = "Incline Skull Crusher"
    _45_DEGREE_LYING_TRICEP_EXTENSION = "45 Degree Lying Tricep Extension"
    ONEARM_SEATED_DUMBBELL_EXTENSION = "OneArm Seated Dumbbell Extension"
    REVERSE_GRIP_CABLE_TRICEP_EXTENSION = "Reverse Grip Cable Tricep Extension"
    BENCH_DIP = "Bench Dip"
    HIGH_PULLEY_OVERHEAD_TRICEP_EXTENSION_ROPE_EXTENSION = "High Pulley Overhead Tricep Extension Rope Extension"
    WEIGHTED_TRICEP_DIPS = "Weighted Tricep Dips"
    SEATED_FRENCH_PRESS = "Seated French Press"
    ONEARM_CABLE_TRICEP_EXTENSION = "OneArm Cable Tricep Extension"
    CLOSE_GRIP_PUSH_UP = "Close Grip Push Up"
    STANDING_OVERHEAD_EZ_BAR_TRICEP_EXTENSION = "Standing Overhead EZ Bar Tricep Extension"
    REVERSE_ONEARM_CABLE_TRICEP_EXTENSION = "Reverse OneArm Cable Tricep Extension"
    ONE_ARM_KETTLEBELL_FLOOR_PRESS = "One Arm Kettlebell Floor Press"
    HIGH_PULLEY_OVERHEAD_TRICEP_EXTENSION = "High Pulley Overhead Tricep Extension"
    CABLE_TRICEP_EXTENSION_WITH_VBAR = "Cable Tricep Extension With VBar"

    
class Equipment(str, Enum):
    '''Enum for Equipment values.'''

    MACHINE = "Machine"
    CABLE = "Cable"
    BODYWEIGHT = "Bodyweight"
    OTHER = "Other"
    DUMBBELL = "Dumbbell"
    BARBELL = "Barbell"
    EXERCISE_BALL = "Exercise Ball"
    KETTLE_BELLS = "Kettle Bells"
    VALSLIDE = "Valslide"
    MEDICINE_BALL = "Medicine Ball"
    BANDS = "Bands"
    FOAM_ROLL = "Foam Roll"
    EZ_BAR = "EZ Bar"
    SLED = "Sled"
    JUMP_ROPE = "Jump Rope"
    TIGER_TAIL = "Tiger Tail"
    BENCH = "Bench"
    RINGS = "Rings"
    CHAINS = "Chains"
    LACROSSE_BALL = "Lacrosse Ball"
    TRAP_BAR = "Trap Bar"
    HIP_THRUSTER = "Hip Thruster"
    LANDMINE = "Landmine"
    FAT_BAR = "Fat Bar"
    ROPE = "Rope"
    BOX = "Box"
    SAFETY_BAR = "Safety Bar"
    TIRE = "Tire"

    
class Type(str, Enum):
    '''Enum for Type values.'''

    STRENGTH = "Strength"
    SMR = "SMR"
    WARMUP = "Warmup"
    CONDITIONING = "Conditioning"
    POWERLIFTING = "Powerlifting"
    PLYOMETRICS = "Plyometrics"
    ACTIVATION = "Activation"
    OLYMPIC_WEIGHTLIFTING = "Olympic Weightlifting"
    STRETCHING = "Stretching"
    STRONGMAN = "Strongman"

    
class MuscleGroup(str, Enum):
    '''Enum for MuscleGroup values.'''

    LEGS = "Legs"
    ABS = "Abs"
    BICEPS = "Biceps"
    CHEST = "Chest"
    BACK = "Back"
    SHOULDERS = "Shoulders"
    TRICEPS = "Triceps"

    
class Difficulty(str, Enum):
    '''Enum for Difficulty values.'''

    BEGINNER = "Beginner"
    INTERMEDIATE = "Intermediate"
    ADVANCED = "Advanced"

    
class Goal(str, Enum):
    '''Enum for Goal values.'''

    BUILD_MUSCLE = "Build Muscle"
    INCREASE_STRENGTH = "Increase Strength"
    LOSE_FAT = "Lose Fat"
    GENERAL_FITNESS = "General Fitness"
    SPORTS_PERFORMANCE = "Sports Performance"
    INCREASE_ENDURANCE = "Increase Endurance"

    